const {execFileSync}=require('child_process');
const fs=require('fs'),path=require('path');
const fallback=path.resolve(__dirname,'../cie-daily-commercial/.tools/imageio_ffmpeg/binaries/ffmpeg-win-x86_64-v7.1.exe');
const ff=process.env.FFMPEG_PATH || (fs.existsSync(fallback)?fallback:'ffmpeg');
const file=process.argv[2]||'out/breakpoint_launch_master_1080x1920_60fps.mp4';
const probe=require('child_process').spawnSync(ff,['-hide_banner','-i',file,'-map','0:v:0','-vf','showinfo','-an','-f','null','-'],{encoding:'utf8',maxBuffer:20*1024*1024});
if(probe.status!==0)throw new Error(probe.stderr);
const frames=[...probe.stderr.matchAll(/n:\s*(\d+) pts:\s*\d+ pts_time:([\d.]+)/g)].map(m=>({index:Number(m[1]),time:Number(m[2])}));
if(frames.length!==1740)throw new Error('Wrong frame count: '+frames.length);
for(let i=0;i<frames.length;i++)if(frames[i].index!==i||Math.abs(frames[i].time-i/60)>.00011)throw new Error('Nonuniform frame timestamp at '+i);
if(!probe.stderr.includes('s:1080x1920'))throw new Error('Wrong resolution');
const sha256=require('crypto').createHash('sha256').update(fs.readFileSync(file)).digest('hex');
fs.writeFileSync('review/technical-verification.json',JSON.stringify({file,frames:1740,width:1080,height:1920,fps:60,durationSeconds:29,consecutiveTimestamps:true,sha256},null,2));
console.log('Verified 1740 consecutive frames, 1080x1920, uniform 60 fps:',file);
const result=require('child_process').spawnSync(ff,['-hide_banner','-i',file,'-af','ebur128=peak=true','-vn','-f','null','-'],{encoding:'utf8',maxBuffer:4*1024*1024});
if(result.status!==0)throw new Error(result.stderr);
fs.writeFileSync('review/audio-measurement.txt',result.stderr);
console.log(result.stderr.slice(-1000));
