import React from 'react';
import {AbsoluteFill, Easing, Img, OffthreadVideo, staticFile, interpolate, useCurrentFrame} from 'remotion';
export const C = {ink:'#080B0C',graphite:'#171B1F',bone:'#EDE9E0',orange:'#FF6A1A',muted:'#8C9294'};
export const ease = Easing.bezier(.22,1,.36,1);
export const between=(f:number,a:number,b:number,x:number,y:number)=>interpolate(f,[a,b],[x,y],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
export const Dot=({size=22,style={}}:{size?:number,style?:React.CSSProperties})=><div style={{width:size,height:size,borderRadius:'50%',background:C.orange,flexShrink:0,...style}}/>;
export const Wordmark=({size=100,lockup=true}:{size?:number,lockup?:boolean})=><div style={{display:'flex',alignItems:'center',flexDirection:'column'}}><div style={{display:'flex',alignItems:'center',fontWeight:900,fontSize:size,letterSpacing:size*.022,lineHeight:1}}><span>BREAKP</span><Dot size={size*.58} style={{margin:`0 ${size*.06}px`}}/><span>INT</span></div>{lockup&&<div style={{fontSize:size*.25,letterSpacing:7,marginTop:27}}><span style={{color:C.muted}}>By </span>MANAS</div>}</div>;
export const Environment=()=> <AbsoluteFill style={{background:`radial-gradient(ellipse at 70% 43%, #232a2d 0%, ${C.ink} 68%)`}}><div style={{position:'absolute',left:-300,top:1150,width:1400,height:1000,background:'radial-gradient(ellipse,#FF6A1A0D,transparent 65%)'}}/><div style={{position:'absolute',inset:60,borderTop:'1px solid #ffffff10'}}/></AbsoluteFill>;
export const Copy=({kicker,children,y=220,size=78}:{kicker?:string,children:React.ReactNode,y?:number,size?:number})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:86,right:86,top:y,opacity:between(f,5,26,0,1),transform:`translateY(${between(f,5,42,24,0)}px)`}}>{kicker&&<div style={{fontSize:20,letterSpacing:4,color:C.muted,marginBottom:25,textTransform:'uppercase'}}>{kicker}</div>}<div style={{fontWeight:500,fontSize:size,letterSpacing:-2.5,lineHeight:1.04}}>{children}</div></div>};
export const Phone=({file,still=false,width=644,x=540,y=1130,rx=0,ry=0,rz=0,scale=1,start=0,opacity=1}:{file:string,still?:boolean,width?:number,x?:number,y?:number,rx?:number,ry?:number,rz?:number,scale?:number,start?:number,opacity?:number})=>{
 const h=width*2080/1080;
 return <div style={{position:'absolute',left:x-width/2,top:y-h/2,width,height:h,perspective:2000,opacity,transform:`scale(${scale})`}}><div style={{position:'absolute',inset:0,transform:`rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${rz}deg)`,transformStyle:'preserve-3d'}}>
  <div style={{position:'absolute',inset:-13,borderRadius:width*.09,background:'linear-gradient(120deg,#747a7d,#1c2022 13%,#050708 50%,#424443 91%,#141719)',boxShadow:'25px 45px 80px #000b, -2px 0 1px #ffffff55, 3px 0 2px #FF6A1A28',transform:'translateZ(-7px)'}}/>
  <div style={{position:'absolute',right:-17,top:'25%',width:4,height:65,borderRadius:3,background:'#595b5c'}}/>
  <div style={{position:'absolute',inset:0,borderRadius:width*.073,overflow:'hidden',background:C.ink,border:'2px solid #121719'}}>{still?<Img src={staticFile(`footage/${file}`)} style={{width:'100%',height:'100%'}}/>:<OffthreadVideo muted trimBefore={start} src={staticFile(`footage/${file}`)} style={{width:'100%',height:'100%'}}/>}<div style={{position:'absolute',inset:0,pointerEvents:'none',background:'linear-gradient(118deg,#ffffff05,transparent 35%,transparent 82%,#ffffff03)'}}/></div>
 </div></div>;
};
export const Breakout=({file,width,x,y,angle=0,opacity=1}:{file:string,width:number,x:number,y:number,angle?:number,opacity?:number})=><div style={{position:'absolute',left:x,top:y,width,transform:`perspective(1500px) rotateY(${angle}deg)`,opacity,boxShadow:'0 30px 80px #000b',border:'1px solid #ffffff1c',borderRadius:18,overflow:'hidden'}}><Img src={staticFile(`footage/${file}`)} style={{width:'100%',display:'block'}}/></div>;
export const OrangeWipe=()=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:between(f,0,18,-100,1180),top:0,width:2,height:1920,background:C.orange,opacity:between(f,14,22,1,0)}}/>};
